{
	"version": 1503802037,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/alface-sheet0.png",
		"images/batatafrita-sheet0.png",
		"images/bauru-sheet0.png",
		"images/cevada-sheet0.png",
		"images/maça-sheet0.png",
		"images/melancia-sheet0.png",
		"images/sucodelaranja-sheet0.png",
		"images/rosquinha-sheet0.png",
		"images/pizza-sheet0.png",
		"images/plat-sheet0.png",
		"images/parte1cozinha-sheet0.png",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/bopcoes-sheet0.png",
		"images/hud2-sheet0.png",
		"images/restart1-sheet0.png",
		"images/som-sheet0.png",
		"images/som-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/menup1-sheet0.png",
		"images/informacoes-sheet0.png",
		"images/play-sheet0.png",
		"images/logo-sheet0.png",
		"images/nomedojogo-sheet0.png",
		"images/informa-sheet0.png",
		"images/sprite-sheet0.png",
		"images/parte2czinha-sheet0.png",
		"media/não É proibido - marisa monte (instrumental) (mp3cut.net).m4a",
		"media/não É proibido - marisa monte (instrumental) (mp3cut.net).ogg",
		"media/2 fail.m4a",
		"media/2 fail.ogg",
		"media/9 resposta certa.m4a",
		"media/9 resposta certa.ogg",
		"media/256455_hunter4708_mouse-click (online-audio-converter.com).m4a",
		"media/256455_hunter4708_mouse-click (online-audio-converter.com).ogg",
		"media/177852_motion-s_hit-fx-winding-down (online-audio-converter.com).m4a",
		"media/177852_motion-s_hit-fx-winding-down (online-audio-converter.com).ogg",
		"media/1 resposta certa (mp3cut.net).m4a",
		"media/1 resposta certa (mp3cut.net).ogg",
		"media/meiga e abusada (official instrumental) - anitta (mp3cut.net).m4a",
		"media/meiga e abusada (official instrumental) - anitta (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}