{
	"version": 1520043009,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fundotelaescolha.png",
		"images/tilemap.png",
		"images/solido.png",
		"images/towerdefense_tile-sheet0.png",
		"images/towerdefense_tile-sheet1.png",
		"images/towerdefense_tile-sheet2.png",
		"images/fim-sheet0.png",
		"images/começo-sheet0.png",
		"images/tower_defense-sheet0.png",
		"images/turrent-sheet0.png",
		"images/bala-sheet0.png",
		"images/bala-sheet1.png",
		"images/bala-sheet2.png",
		"images/torre_verde-sheet0.png",
		"images/torre_vermelha-sheet0.png",
		"images/turrentt-sheet0.png",
		"images/particles.png",
		"images/torreespecial-sheet0.png",
		"images/torreespecial2-sheet0.png",
		"images/balaeficiente-sheet0.png",
		"images/bvoltar-sheet0.png",
		"images/nivel1-sheet0.png",
		"images/nivel2-sheet0.png",
		"images/nivel3-sheet0.png",
		"images/tganhou-sheet0.png",
		"images/tperdeu-sheet0.png",
		"images/voltar-sheet0.png",
		"images/fundo1-sheet0.png",
		"images/bplay-sheet0.png",
		"images/bloc1-sheet0.png",
		"media/396765__user391915396__suspense-tension-trap-loop.m4a",
		"media/396765__user391915396__suspense-tension-trap-loop.ogg",
		"media/8 fail.m4a",
		"media/8 fail.ogg",
		"media/9 resposta certa.m4a",
		"media/9 resposta certa.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}